apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: first-gitops-project
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ''
      kind: Pod
    - group: ''
      kind: Service
